### ISSUE TITLE
Command does not exist

### ISSUE THREAD

**Issue by BarbzYHOOL** [jwu910/check-it-out#258] opened 2018-09-28 17:41 UTC
I installed with npm as in the readme but the command is not available

Maybe it does not create a symlink?

Ok while writing this I realized it works in bash but not in Fish. So yes, I guess it does not create a symlink in the user bin dir

**Comment by rainrivas** [comment] 2018-09-28 17:55
Hi @BarbzYHOOL , it is probably just an issue with your Fish config. Others who faced this issue resolved it by adding the global NPM node_modules to their Fish path. 
e.g. `set PATH /Users/{myusername}/{global-npm-folder}/bin $PATH`
By default, this path is added to the Bash PATH which is probably why it works fine in Bash but not Fish. 
To find out exactly where CIO ended up your machine, you can do a `which`, e.g. `$ which cio
/Users/efrain/.nvm/versions/node/v8.11.3/bin/cio`
**NOTE** I have nvm installed, I believe the default path for global node_modules would be the one listed above

**Comment by BarbzYHOOL** [comment] 2018-09-28 18:03
```
which cio
/home/user/npm/bin/cio
```

So what should I do exactly? (with global-npm-folder)
How can I fix the npm path to avoid future headaches?

**Comment by jwu910** [comment] 2018-09-28 18:07
Hi @BarbzYHOOL Did happen to install without the --global flag?

```
[~]$ which cio
/home/joshua/.nvm/versions/node/v8.6.0/bin/cio
```

I currently have mine installed to nvm's bin where my global node modules are installed. I use nvm as sometimes I need to work on different node versions.

If you were installing from source, you can try running `npm link` from the repository root as well.

**Comment by BarbzYHOOL** [comment] 2018-09-28 18:08
I installed with `npm install -g check-it-out`

I don't know anything about npm or nodejs lol

**Comment by jwu910** [comment] 2018-09-28 18:14
https://github.com/fish-shell/fish-shell/issues/3023

@BarbzYHOOL 	You can take a look at this fish issue. Looks like some NPM global installs arent on fish shell path by default.

**Comment by rainrivas** [comment] 2018-09-28 18:14
@BarbzYHOOL thanks for that info, let me find my notes on setting persistent paths in FISH and I'll get back to your question on setting the path permanently.
Could you share what `echo $PATH` prints right now?
Also, in the interim, to fix your current headache, you can do `set PATH set PATH /Users/{myusername}/{global-npm-folder}/bin $PATH` 
However, you'll have to do that every time you launch fish :| (i'll sort that out and see if I can fix it for you).

**Comment by rainrivas** [comment] 2018-09-28 21:38
@BarbzYHOOL let us know if the above comment helped you out

**Comment by jwu910** [comment] 2018-10-01 04:13
@BarbzYHOOL I'm going to close this for now as this doesn't seem to be an issue with Check It Out itself as it worked on your bash shell.

**Closed by jwu910** 2018-10-01 04:13 UTC

**Comment by BarbzYHOOL** [comment] 2018-10-05 17:55
sorry, i'll answer asap, thank you for trying to help me

**Comment by BarbzYHOOL** [comment] 2018-10-06 18:57
Ok thank you for the help, yes I can do it this way but I'm going to discuss on the fish issue because that's annoying that the npm install did not take this into account :)

**Comment by jwu910** [comment] 2018-10-06 20:57
Cool, I hope Check It Out serves you well! Good luck!

Let me know if anything comes up.

**Comment by BarbzYHOOL** [comment] 2018-10-07 10:50
Is it normal that when I invoke "cio" it takes 9 seconds to show up for 2 branches (at least the first time, then it took 700ms) ?

**Comment by jwu910** [comment] 2018-10-07 19:00
I have only experienced longer load times on my repositories with 30k+ refs. All of my other smaller projects have loaded Check It Out almost instantaneously. Are you able to consistently reproduce the long loading times? If so, please open a new issue and provide information about your environment and steps to reproduce.

Thanks!

**Comment by BarbzYHOOL** [comment] 2018-10-08 17:53
Yeah, even in bash but I don't know, I don't have a lot of time to spend on this, sorry lol. Especially since I'm doing nothing special, just "cio" in a 180 commit repo, nothing else. I can live with it for now
